# Generated by Django 3.2.4 on 2021-06-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedaidea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='patsimage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
