# Generated by Django 3.2.4 on 2021-06-14 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedaidea', '0002_image_patsimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='patsimage',
            new_name='pathimage',
        ),
    ]
