# Generated by Django 3.2.4 on 2021-07-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedaidea', '0002_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='image',
        ),
        migrations.AddField(
            model_name='report',
            name='imageReport',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
