# Generated by Django 3.2.4 on 2021-07-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedaidea', '0004_rename_imagereport_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pathoraclecloud',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
